services:
  - type: web
    name: comment-auto
    env: node
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-137.0.7151.55/chrome
